### ISSUE TITLE
Move State of Our Networks repo to new GitHub Org: "ournetworks"

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2017-mini-conf#26]
In advance of planning a 2018 State of Our Networks, I was thinking it would be nice to move to a separate GH org: https://github.com/ournetworks, and register a new domain (I'm thinking like stateof.ournetworks.ca/2018)...

There are a couple reasons:
- I think it would be easier to keep together the materials across the year without all the other tomesh projects
- Helps set us up recruiting for people outside tomesh onto the organizing committee

Any tomesh people who want to be added/involved in planning are welcome!

**Comment by dcwalk** [comment]
Hey @garrying -- what do you think? I know we briefly talked about a SooN 2018 edition

**Comment by garrying** [comment]
I think it makes sense. This affords some flexibility with multiple/parallel SooN events and org specific projects which would be radical if that is part of the medium-long term plan.

**Comment by dcwalk** [comment]
Okie! That is kinda part of the long-term plan (pattern that others can take and run with elsewhere? but also having a toronto anchor!)

Hearing no objections here or in tomesh chat I'm gonna do this
