### ISSUE TITLE
Logistics

### ISSUE THREAD

**Issue by dcwalk** [ournetworks/2017-mini-conf#4]
Tracking issue for logistics (including day-of):

**Requirements**
- Registration, cost (?), all details from speakers
- Details for event

**Pre-event TODOs**
- [x] Set up registration (**early Dec**)
- [x] First version event website (**early Dec**)
- [x] Sticker design challenge announcement (**Dec 14** December 14-20)
- [x] Sticker design challenge voting period announcement (**Dec 21** December 21-28)
- [x] Request wifi access for event (**late Dec**)
  - emailed 2016-10-18
- [x] Second version event website (**late Dec**)
- [x] **ORDER STICKERS!** Sticker design ordered (**Dec 29**)
- [x] Ensure all required materials for sessions secured (materials sheet) (**early Jan**)
- [x] Arrange for volunteers (**early Jan**)
  - [x] Morning registration: @dcwalk @structur 
  - [x] Breakdown: @dcwalk; remaining participants

**Week prior TODOs** _WIP_
- [x] Speaker emails (**Jan 7**)
  - [x] Session E (intro moderator; 'questions'; details)
  - [X] Session F (prep; details)
- [x] Registration: final schedule email! (**Jan 8**)
- [x] Registration: reminder email & social event reminder
- [x] Make day-of runsheet (**early Jan**)
  - [x] Stickers (cut)
  - [x] Direction signage
  - [x] Workshop materials: 10x breadboards; 10x ethernet cables
  - [x] Projector adaptor and laptop
  - [x] Session F materials: 
     - [x] Printouts: 20x Problem Tree; Fast Idea Generator
     - [x] Printouts: Project Pitch

**Day-of TODOs** _WIP_
- [x] Signage up
- [x] Registration Desk
- [x] Monitor Inforum Access until 10am

**Comment by dcwalk** [comment]
RE: stickers, I think we can expect it to cost in the ~$66 - 100 range for 100 - 300 stickers.

Places to order stickers with tomesh logos:
- https://www.stickercanada.com/custom/stickers/bumper-stickers
- https://www.stickermule.com/products/circle-stickers
- http://www.stickeryou.com/2/about-stickeryou/pricing-stickers-labels

**Comment by ansuz** [comment]
YAY STICKERS

**Comment by dcwalk** [comment]
Adding sticker challenge details below:

Lend tomesh your **sticker design** skills! As discussed we are having a voting competition to print up to 2 sticker designs for the upcoming conference and Toronto Mesh. Submit **as many designs** as you want between **Dec 14-20** either in `#stickers:tomesh.net` or ping me for posting in the channel.
We'll have a ranked vote from **Dec 21-28** to determine the top two designs. Designs requirements further specified in the channel, basically hi-res, print-ready, open license-friendly!

_Winning designs will not become our logo, but hopefully will work into a larger conversation about logos and Toronto Mesh visual appearance._

Dates:
Design Submission Period: December 14-20
Voting Period: December 21-28
Order Date: December 29

Design Requirements:
1. Dimensions should be at minimum 1.5"x1.5" and smaller than 8.5"x5.5"
2. Ideally 4 colours or less
3. Hi-resolution images in editable file (`.eps`, `.ai`, `.indd`)
4. Images and text that can be released under a Creative Commons license
5. Ideally dimensions, bleeds, and die-cut (shape of sticker) indicated

**Comment by dcwalk** [comment]
Stickers were ordered Dec 30 and are on their way!
